-- 修復分類與權限問題的腳本
-- 請在 Supabase SQL Editor 中執行此腳本

-- 1. 確保 Categories 的 RLS 政策正確 (允許所有操作)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for categories" ON categories;
CREATE POLICY "Enable all access for categories" ON categories
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- 2. 確保 Products 的 RLS 政策正確
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for products" ON products;
CREATE POLICY "Enable all access for products" ON products
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- 3. 確保 categories.id 是自動遞增 (Identity)
-- 如果您手動建立 Table 但沒有勾選 Identity，插入時會失敗
DO $$
BEGIN
  -- 檢查 id 是否已經是 identity column ( 'a' = always, 'd' = by default)
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = 'categories'::regclass
    AND attname = 'id'
    AND attidentity IN ('a', 'd')
  ) THEN
    -- 如果不是，則將其設為 Identity
    ALTER TABLE categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;
